import React, { Component } from 'react'

export default class Projects extends Component {
  render() {
    return (
      <div className="fullheight">
        <h1>PROYECTOS</h1>
        <section>
          <div id="foo1">
          See. We take the corner of the brush and let it play back-and-forth. Be careful. You can always add more - but you can't take it away. You can do it. We'll play with clouds today. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen. A thin paint will stick to a thick paint. Isn't that fantastic that you can make whole mountains in minutes? Everything's not great in life, but we can still find beauty in it. All you need is a dream in your heart, and an almighty knife. Let's make some happy little clouds in our world. It's important to me that you're happy. These little son of a guns hide in your brush and you just have to push them out.

We have a fantastic little sky! It's all a game of angles. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. That's what painting is all about. It should make you feel good when you paint. Maybe there's a little something happening right here. All those little son of a guns. Son of a gun. You create the dream - then you bring it into your world. It just happens - whether or not you worried about it or tried to plan it. A tree needs to be your friend if you're going to paint him.

God gave you this gift of imagination. Use it. In your imagination you can go anywhere you want. There we go. Just let your mind wander and enjoy. This should make you happy. Just think about these things in your mind - then bring them into your world. It's a good way of getting rid of all your anxieties and hostilities. Remember how free clouds are. They just lay around in the sky all day long. We don't have to be committed. We are just playing here. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. And just raise cain. What the devil. You want your tree to have some character. Make it special. It all happens automatically. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. Life is too short to be alone, too precious. Share it with a friend.

Work that paint. But they're very easily killed. Clouds are delicate. And maybe, maybe, maybe... Give him a friend, we forget the trees get lonely too. A little happy sunlight shining through there. Only God can make a tree - but you can paint one. In your world you have total and absolute power. This is the fun part Now we'll take the almighty fan brush. Imagination is the key to painting.

If these lines aren't straight, your water's going to run right out of your painting and get your floor wet. We start with a vision in our heart, and we put it on canvas. Let's do that again. Think about a cloud. Just float around and be there. It is a lot of fun. If you do too much it's going to lose its effectiveness. Just make little strokes like that. You better get your coat out, this is going to be a cold painting. These things happen automatically. All you have to do is just let them happen. It's cold, but it's beautiful. This is a happy place, little squirrels live here and play. I will take some magic white, and a little bit of Vandyke brown and a little touch of yellow. Maybe we got a few little happy bushes here, just covered with snow. The shadows are just like the highlights, but we're going in the opposite direction.

As trees get older they lose their chlorophyll. We spend so much of our life looking - but never seeing. If you don't think every day is a good day - try missing a few. You'll see. It's a super day, so why not make a beautiful sky? Just a little indication. That is when you can experience true joy, when you have no fear. You're meant to have fun in life. I'll go over the colors one more time that we use: Titanium white, Thalo green, Prussian blue, Van Dyke brown, Alizarin crimson, Sap green, Cad yellow, and Permanent red. We'll paint one happy little tree right here. We don't have anything but happy trees here. By now you should be quite happy about what's happening here. Maybe there's a happy little Evergreen that lives here. Now it's beginning to make a little sense. We can always carry this a step further. There's really no end to this.

Pretend you're water. Just floating without any effort. Having a good day. That's why I paint - because I can create the kind of world I want - and I can make this world as happy as I want it. Trees cover up a multitude of sins. This is truly an almighty mountain. Let's make some happy little clouds in our world. There it is. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. It takes dark in order to show light. From all of us here, I want to wish you happy painting and God bless, my friends. Don't be bashful drop me a line. That's what makes life fun. That you can make these decisions. That you can create the world that you want. Nice little fluffy clouds laying around in the sky being lazy. Nothing's gonna make your husband or wife madder than coming home and having a snow-covered dinner.

We need a shadow side and a highlight side. Let's get wild today. It's so important to do something every day that will make you happy. This piece of canvas is your world. I'm gonna start with a little Alizarin crimson and a touch of Prussian blue You can create anything that makes you happy. Just let this happen. We just let this flow right out of our minds. Don't hurry. Take your time and enjoy. Very easy to work these to death. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right.

Get tough with it, get strong. This is the way you take out your flustrations. Put light against light - you have nothing. Put dark against dark - you have nothing. It's the contrast of light and dark that each give the other one meaning. You can get away with a lot. Let's put some happy trees and bushes back in here. Only eight colors that you need. Clouds are free. They just float around the sky all day and have fun. That's a son of a gun of a cloud. Everyone needs a friend. Friends are the most valuable things in the world. Let that brush dance around there and play.

Isn't that fantastic that you can create an almighty tree that fast? In your world you can create anything you desire. Don't kill all your dark areas - you need them to show the light. Work on one thing at a time. Don't get carried away - we have plenty of time. Only think about one thing at a time. Don't get greedy. Decide where your cloud lives. Maybe he lives right in here. I really recommend you use odorless thinner or your spouse is gonna run you right out into the yard and you'll be working by yourself. Talk to trees, look at the birds. Whatever it takes. We artists are a different breed of people. We're a happy bunch. Making all those little fluffies that live in the clouds. You can do anything here. So don't worry about it. Let your imagination be your guide. This is unplanned it really just happens. The least little bit can do so much. Just let these leaves jump off the brush

Now we don't want him to get lonely, so we'll give him a little friend. That's the way I look when I get home late; black and blue. This is a fantastic little painting. I thought today we would make a happy little stream that's just running through the woods here. Follow the lay of the land. It's most important. You have freedom here. The only guide is your heart. Poor old tree. All you have to learn here is how to have fun. How do you make a round circle with a square knife? That's your challenge for the day. Happy painting, God bless.

Let's get crazy. Let's build an almighty mountain. See there how easy that is. There we are. Use what happens naturally, don't fight it. We're trying to teach you a technique here and how to use it. Maybe there's a happy little waterfall happening over here. That's crazy. We'll throw some happy little limbs on this tree. We don't want to set these clouds on fire. It's hard to see things when you're too close. Take a step back and look. You have to make these big decisions. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a happy little tree in here.

Working it up and down, back and forth. This is your world. Just let go - and fall like a little waterfall. Maybe, just to play a little, we'll put a little tree here. All you need to paint is a few tools, a little instruction, and a vision in your mind. Let your imagination just wonder around when you're doing these things. Use what you see, don't plan it. Everything is happy if you choose to make it that way. Let's make a happy little mountain now. Automatically, all of these beautiful, beautiful things will happen. We'll take a little bit of Van Dyke Brown. You don't have to be crazy to do this but it does help. If we're going to have animals around we all have to be concerned about them and take care of them.

You could sit here for weeks with your one hair brush trying to do that - or you could do it with one stroke with an almighty brush. Here's something that's fun. I sincerely wish for you every possible joy life could bring. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You have to make those little noises or it won't work. Any little thing can be your friend if you let it be. The very fact that you're aware of suffering is enough reason to be overjoyed that you're alive and can experience it. Exercising the imagination, experimenting with talents, being creative; these things, to me, are truly the windows to your soul. Let's have a nice tree right here. If you overwork it you become a cloud killer. There's nothing worse than a cloud killer. There comes a nice little fluffer. Here we're limited by the time we have. Steve wants reflections, so let's give him reflections.

You've got to learn to fight the temptation to resist these things. Just let them happen. Of course he's a happy little stone, cause we don't have any other kind. Everyone wants to enjoy the good parts - but you have to build the framework first. It's beautiful - and we haven't even done anything to it yet. I think there's an artist hidden in the bottom of every single one of us. When things happen - enjoy them. They're little gifts. If you don't like it - change it. It's your world. There he comes. You don't want to kill all your dark areas they are very important. In nature, dead trees are just as normal as live trees. A happy cloud. Use your imagination, let it go. This painting comes right out of your heart. There we go. I'm a water fanatic. I love water.


          </div>
          <div id="foo2">
          That's what painting is all about. It should make you feel good when you paint. We have a fantastic little sky! If you do too much it's going to lose its effectiveness. If you hypnotize it, it will go away. This is the way you take out your flustrations. You can do anything your heart can imagine. Just let these leaves jump off the brush Just use the old one inch brush. Trees live in your fan brush, but you have to scare them out. Mix your color marbly don't mix it dead. Be careful. You can always add more - but you can't take it away. Let's make some happy little clouds in our world. There comes a nice little fluffer. Let's put some happy trees and bushes back in here.

Just beat the devil out of it. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a nice tree right here. Have fun with it. Just make a decision and let it go. With practice comes confidence. I sincerely wish for you every possible joy life could bring. Pretend you're water. Just floating without any effort. Having a good day. No worries. No cares. Just float and wait for the wind to blow you around. Maybe there's a little something happening right here. You can do anything here - the only pre-requisite is that it makes you happy.

Even trees need a friend. We all need friends. Everybody needs a friend. See there, told you that would be easy. So often we avoid running water, and running water is a lot of fun. There are no mistakes. You can fix anything that happens. In your world you have total and absolute power. Tree trunks grow however makes them happy. Maybe there's a happy little Evergreen that lives here. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. I thought today we would make a happy little stream that's just running through the woods here. Work on one thing at a time. Don't get carried away - we have plenty of time. A fan brush can be your best friend. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.

Learn when to stop. They say everything looks better with odd numbers of things. But sometimes I put even numbers—just to upset the critics. There we go. This is truly an almighty mountain. Think about a cloud. Just float around and be there. God gave you this gift of imagination. Use it. Get away from those little Christmas tree things we used to make in school. Imagination is the key to painting. Decide where your cloud lives. Maybe he lives right in here. Let that brush dance around there and play. We'll throw some happy little limbs on this tree. Isn't it great to do something you can't fail at? Let's go up in here, and start having some fun

We don't need any guidelines or formats. All we need to do is just let it flow right out of us. Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect. We'll put a happy little bush here. See. We take the corner of the brush and let it play back-and-forth. Don't forget to tell these special people in your life just how special they are to you. Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying. We start with a vision in our heart, and we put it on canvas. Isn't that fantastic that you can create an almighty tree that fast? There isn't a rule. You just practice and find out which way works best for you. It's almost like something out of a fairytale book. I'm a water fanatic. I love water. You can create anything that makes you happy. I thought today we would do a happy little picture. Isn't that fantastic? You can just push a little tree out of your brush like that.

I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things. Here's something that's fun. You better get your coat out, this is going to be a cold painting. These trees are so much fun. I get started on them and I have a hard time stopping. Just take out whatever you don't want. It'll change your entire perspective. Maybe there's a happy little waterfall happening over here. Here we're limited by the time we have. Absolutely no pressure. You are just a whisper floating across a mountain. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You are only limited by your imagination.

In your imagination you can go anywhere you want. There we go. Without washing the brush, I'm gonna go right into some Van Dyke Brown, some Burnt Umber, and a little bit of Sap Green. Steve wants reflections, so let's give him reflections. Little short strokes. Put your feelings into it, your heart, it's your world. In your world you can create anything you desire. The least little bit can do so much. Don't be bashful drop me a line. A beautiful little sunset. Don't kill all your dark areas - you need them to show the light. From all of us here, I want to wish you happy painting and God bless, my friends.

We don't really know where this goes - and I'm not sure we really care. If what you're doing doesn't make you happy - you're doing the wrong thing. You can spend all day playing with mountains. Just go out and talk to a tree. Make friends with it. You create the dream - then you bring it into your world. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. Isn't it fantastic that you can change your mind and create all these happy things? Just make little strokes like that. Let's put some highlights on these little trees. The sun wouldn't forget them. You've got to learn to fight the temptation to resist these things. Just let them happen. There are no limits in this world. Let your imagination be your guide. Let all these things just sort of happen. You can work and carry-on and put lots of little happy things in here. If it's not what you want - stop and change it. Don't just keep going and expect it will get better.

Let's put some happy little bushes on the other side now. Let your imagination be your guide. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. You're meant to have fun in life. You have to make those little noises or it won't work. Let's get crazy. Making all those little fluffies that live in the clouds. But we're not there yet, so we don't need to worry about it. Water's like me. It's laaazy ... Boy, it always looks for the easiest way to do things That's crazy. Every time you practice, you learn more. Just relax and let it flow. That easy.

We'll take a little bit of Van Dyke Brown. Only God can make a tree - but you can paint one. That's what makes life fun. That you can make these decisions. That you can create the world that you want. If you don't think every day is a good day - try missing a few. You'll see. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right. Just think about these things in your mind and drop em' on canvas. It's beautiful - and we haven't even done anything to it yet. Clouds are free. They just float around the sky all day and have fun. Now then, let's play. It is a lot of fun. Don't fiddle with it all day. Painting should do one thing. It should put happiness in your heart. We'll put all the little clouds in and let them dance around and have fun. This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.

Let's do that again. There it is. Everything's not great in life, but we can still find beauty in it. Now we don't want him to get lonely, so we'll give him a little friend. Let's get wild today. The little tiny Tim easels will let you down. We touch the canvas, the canvas takes what it wants. The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start. We don't make mistakes we just have happy little accidents. Look at them little rascals. It looks so good, I might as well not stop. All you need to paint is a few tools, a little instruction, and a vision in your mind. You gotta think like a tree.

And maybe, maybe, maybe... That easy. This is probably the greatest thing that's ever happened in my life. And maybe a little bush lives there. This is probably the greatest thing to happen in my life - to be able to share this with you. You don't have to be crazy to do this but it does help. You can create beautiful things - but you have to see them in your mind first. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. Use your imagination, let it go. There we are. This present moment is perfect simply due to the fact you're experiencing it. We'll have a super time. In nature, dead trees are just as normal as live trees. Put it in, leave it alone. But they're very easily killed. Clouds are delicate.

Now we'll take the almighty fan brush. No pressure. Just relax and watch it happen. We'll lay all these little funky little things in there. A big strong tree needs big strong roots. Everyone wants to enjoy the good parts - but you have to build the framework first. We're trying to teach you a technique here and how to use it. We can always carry this a step further. There's really no end to this. This is a happy place, little squirrels live here and play. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. We need a shadow side and a highlight side. Be so very light. Be a gentle whisper.

There's nothing wrong with having a tree as a friend. You need the dark in order to show the light. Fluff that up. When you buy that first tube of paint it gives you an artist license. Everyone is going to see things differently - and that's the way it should be. Anytime you learn something your time and energy are not wasted. All you have to learn here is how to have fun. Brown is such a nice color. The only prerequisite is that it makes you happy. If it makes you happy then it's good. We want to use a lot pressure while using no pressure at all. Don't fight it, use what happens. All you have to do is let your imagination go wild. Just go back and put one little more happy tree in there.

It's a super day, so why not make a beautiful sky? Very easy to work these to death. How do you make a round circle with a square knife? That's your challenge for the day. A happy cloud. Give him a friend, we forget the trees get lonely too. Just let this happen. We just let this flow right out of our minds. You can't have light without dark. You can't know happiness unless you've known sorrow. That's the way I look when I get home late; black and blue. Sometimes you learn more from your mistakes than you do from your masterpieces. Work that paint. Trees get lonely too, so we'll give him a little friend.


          </div>
          <div id="foo3">
That's what painting is all about. It should make you feel good when you paint. We have a fantastic little sky! If you do too much it's going to lose its effectiveness. If you hypnotize it, it will go away. This is the way you take out your flustrations. You can do anything your heart can imagine. Just let these leaves jump off the brush Just use the old one inch brush. Trees live in your fan brush, but you have to scare them out. Mix your color marbly don't mix it dead. Be careful. You can always add more - but you can't take it away. Let's make some happy little clouds in our world. There comes a nice little fluffer. Let's put some happy trees and bushes back in here.

Just beat the devil out of it. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a nice tree right here. Have fun with it. Just make a decision and let it go. With practice comes confidence. I sincerely wish for you every possible joy life could bring. Pretend you're water. Just floating without any effort. Having a good day. No worries. No cares. Just float and wait for the wind to blow you around. Maybe there's a little something happening right here. You can do anything here - the only pre-requisite is that it makes you happy.

Even trees need a friend. We all need friends. Everybody needs a friend. See there, told you that would be easy. So often we avoid running water, and running water is a lot of fun. There are no mistakes. You can fix anything that happens. In your world you have total and absolute power. Tree trunks grow however makes them happy. Maybe there's a happy little Evergreen that lives here. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. I thought today we would make a happy little stream that's just running through the woods here. Work on one thing at a time. Don't get carried away - we have plenty of time. A fan brush can be your best friend. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.

Learn when to stop. They say everything looks better with odd numbers of things. But sometimes I put even numbers—just to upset the critics. There we go. This is truly an almighty mountain. Think about a cloud. Just float around and be there. God gave you this gift of imagination. Use it. Get away from those little Christmas tree things we used to make in school. Imagination is the key to painting. Decide where your cloud lives. Maybe he lives right in here. Let that brush dance around there and play. We'll throw some happy little limbs on this tree. Isn't it great to do something you can't fail at? Let's go up in here, and start having some fun

We don't need any guidelines or formats. All we need to do is just let it flow right out of us. Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect. We'll put a happy little bush here. See. We take the corner of the brush and let it play back-and-forth. Don't forget to tell these special people in your life just how special they are to you. Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying. We start with a vision in our heart, and we put it on canvas. Isn't that fantastic that you can create an almighty tree that fast? There isn't a rule. You just practice and find out which way works best for you. It's almost like something out of a fairytale book. I'm a water fanatic. I love water. You can create anything that makes you happy. I thought today we would do a happy little picture. Isn't that fantastic? You can just push a little tree out of your brush like that.

I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things. Here's something that's fun. You better get your coat out, this is going to be a cold painting. These trees are so much fun. I get started on them and I have a hard time stopping. Just take out whatever you don't want. It'll change your entire perspective. Maybe there's a happy little waterfall happening over here. Here we're limited by the time we have. Absolutely no pressure. You are just a whisper floating across a mountain. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You are only limited by your imagination.

In your imagination you can go anywhere you want. There we go. Without washing the brush, I'm gonna go right into some Van Dyke Brown, some Burnt Umber, and a little bit of Sap Green. Steve wants reflections, so let's give him reflections. Little short strokes. Put your feelings into it, your heart, it's your world. In your world you can create anything you desire. The least little bit can do so much. Don't be bashful drop me a line. A beautiful little sunset. Don't kill all your dark areas - you need them to show the light. From all of us here, I want to wish you happy painting and God bless, my friends.

We don't really know where this goes - and I'm not sure we really care. If what you're doing doesn't make you happy - you're doing the wrong thing. You can spend all day playing with mountains. Just go out and talk to a tree. Make friends with it. You create the dream - then you bring it into your world. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. Isn't it fantastic that you can change your mind and create all these happy things? Just make little strokes like that. Let's put some highlights on these little trees. The sun wouldn't forget them. You've got to learn to fight the temptation to resist these things. Just let them happen. There are no limits in this world. Let your imagination be your guide. Let all these things just sort of happen. You can work and carry-on and put lots of little happy things in here. If it's not what you want - stop and change it. Don't just keep going and expect it will get better.

Let's put some happy little bushes on the other side now. Let your imagination be your guide. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. You're meant to have fun in life. You have to make those little noises or it won't work. Let's get crazy. Making all those little fluffies that live in the clouds. But we're not there yet, so we don't need to worry about it. Water's like me. It's laaazy ... Boy, it always looks for the easiest way to do things That's crazy. Every time you practice, you learn more. Just relax and let it flow. That easy.

We'll take a little bit of Van Dyke Brown. Only God can make a tree - but you can paint one. That's what makes life fun. That you can make these decisions. That you can create the world that you want. If you don't think every day is a good day - try missing a few. You'll see. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right. Just think about these things in your mind and drop em' on canvas. It's beautiful - and we haven't even done anything to it yet. Clouds are free. They just float around the sky all day and have fun. Now then, let's play. It is a lot of fun. Don't fiddle with it all day. Painting should do one thing. It should put happiness in your heart. We'll put all the little clouds in and let them dance around and have fun. This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.

Let's do that again. There it is. Everything's not great in life, but we can still find beauty in it. Now we don't want him to get lonely, so we'll give him a little friend. Let's get wild today. The little tiny Tim easels will let you down. We touch the canvas, the canvas takes what it wants. The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start. We don't make mistakes we just have happy little accidents. Look at them little rascals. It looks so good, I might as well not stop. All you need to paint is a few tools, a little instruction, and a vision in your mind. You gotta think like a tree.

And maybe, maybe, maybe... That easy. This is probably the greatest thing that's ever happened in my life. And maybe a little bush lives there. This is probably the greatest thing to happen in my life - to be able to share this with you. You don't have to be crazy to do this but it does help. You can create beautiful things - but you have to see them in your mind first. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. Use your imagination, let it go. There we are. This present moment is perfect simply due to the fact you're experiencing it. We'll have a super time. In nature, dead trees are just as normal as live trees. Put it in, leave it alone. But they're very easily killed. Clouds are delicate.

Now we'll take the almighty fan brush. No pressure. Just relax and watch it happen. We'll lay all these little funky little things in there. A big strong tree needs big strong roots. Everyone wants to enjoy the good parts - but you have to build the framework first. We're trying to teach you a technique here and how to use it. We can always carry this a step further. There's really no end to this. This is a happy place, little squirrels live here and play. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. We need a shadow side and a highlight side. Be so very light. Be a gentle whisper.

There's nothing wrong with having a tree as a friend. You need the dark in order to show the light. Fluff that up. When you buy that first tube of paint it gives you an artist license. Everyone is going to see things differently - and that's the way it should be. Anytime you learn something your time and energy are not wasted. All you have to learn here is how to have fun. Brown is such a nice color. The only prerequisite is that it makes you happy. If it makes you happy then it's good. We want to use a lot pressure while using no pressure at all. Don't fight it, use what happens. All you have to do is let your imagination go wild. Just go back and put one little more happy tree in there.

It's a super day, so why not make a beautiful sky? Very easy to work these to death. How do you make a round circle with a square knife? That's your challenge for the day. A happy cloud. Give him a friend, we forget the trees get lonely too. Just let this happen. We just let this flow right out of our minds. You can't have light without dark. You can't know happiness unless you've known sorrow. That's the way I look when I get home late; black and blue. Sometimes you learn more from your mistakes than you do from your masterpieces. Work that paint. Trees get lonely too, so we'll give him a little friend.


          </div>
          <div id="foo4">
That's what painting is all about. It should make you feel good when you paint. We have a fantastic little sky! If you do too much it's going to lose its effectiveness. If you hypnotize it, it will go away. This is the way you take out your flustrations. You can do anything your heart can imagine. Just let these leaves jump off the brush Just use the old one inch brush. Trees live in your fan brush, but you have to scare them out. Mix your color marbly don't mix it dead. Be careful. You can always add more - but you can't take it away. Let's make some happy little clouds in our world. There comes a nice little fluffer. Let's put some happy trees and bushes back in here.

Just beat the devil out of it. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a nice tree right here. Have fun with it. Just make a decision and let it go. With practice comes confidence. I sincerely wish for you every possible joy life could bring. Pretend you're water. Just floating without any effort. Having a good day. No worries. No cares. Just float and wait for the wind to blow you around. Maybe there's a little something happening right here. You can do anything here - the only pre-requisite is that it makes you happy.

Even trees need a friend. We all need friends. Everybody needs a friend. See there, told you that would be easy. So often we avoid running water, and running water is a lot of fun. There are no mistakes. You can fix anything that happens. In your world you have total and absolute power. Tree trunks grow however makes them happy. Maybe there's a happy little Evergreen that lives here. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. I thought today we would make a happy little stream that's just running through the woods here. Work on one thing at a time. Don't get carried away - we have plenty of time. A fan brush can be your best friend. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.

Learn when to stop. They say everything looks better with odd numbers of things. But sometimes I put even numbers—just to upset the critics. There we go. This is truly an almighty mountain. Think about a cloud. Just float around and be there. God gave you this gift of imagination. Use it. Get away from those little Christmas tree things we used to make in school. Imagination is the key to painting. Decide where your cloud lives. Maybe he lives right in here. Let that brush dance around there and play. We'll throw some happy little limbs on this tree. Isn't it great to do something you can't fail at? Let's go up in here, and start having some fun

We don't need any guidelines or formats. All we need to do is just let it flow right out of us. Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect. We'll put a happy little bush here. See. We take the corner of the brush and let it play back-and-forth. Don't forget to tell these special people in your life just how special they are to you. Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying. We start with a vision in our heart, and we put it on canvas. Isn't that fantastic that you can create an almighty tree that fast? There isn't a rule. You just practice and find out which way works best for you. It's almost like something out of a fairytale book. I'm a water fanatic. I love water. You can create anything that makes you happy. I thought today we would do a happy little picture. Isn't that fantastic? You can just push a little tree out of your brush like that.

I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things. Here's something that's fun. You better get your coat out, this is going to be a cold painting. These trees are so much fun. I get started on them and I have a hard time stopping. Just take out whatever you don't want. It'll change your entire perspective. Maybe there's a happy little waterfall happening over here. Here we're limited by the time we have. Absolutely no pressure. You are just a whisper floating across a mountain. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You are only limited by your imagination.

In your imagination you can go anywhere you want. There we go. Without washing the brush, I'm gonna go right into some Van Dyke Brown, some Burnt Umber, and a little bit of Sap Green. Steve wants reflections, so let's give him reflections. Little short strokes. Put your feelings into it, your heart, it's your world. In your world you can create anything you desire. The least little bit can do so much. Don't be bashful drop me a line. A beautiful little sunset. Don't kill all your dark areas - you need them to show the light. From all of us here, I want to wish you happy painting and God bless, my friends.

We don't really know where this goes - and I'm not sure we really care. If what you're doing doesn't make you happy - you're doing the wrong thing. You can spend all day playing with mountains. Just go out and talk to a tree. Make friends with it. You create the dream - then you bring it into your world. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. Isn't it fantastic that you can change your mind and create all these happy things? Just make little strokes like that. Let's put some highlights on these little trees. The sun wouldn't forget them. You've got to learn to fight the temptation to resist these things. Just let them happen. There are no limits in this world. Let your imagination be your guide. Let all these things just sort of happen. You can work and carry-on and put lots of little happy things in here. If it's not what you want - stop and change it. Don't just keep going and expect it will get better.

Let's put some happy little bushes on the other side now. Let your imagination be your guide. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. You're meant to have fun in life. You have to make those little noises or it won't work. Let's get crazy. Making all those little fluffies that live in the clouds. But we're not there yet, so we don't need to worry about it. Water's like me. It's laaazy ... Boy, it always looks for the easiest way to do things That's crazy. Every time you practice, you learn more. Just relax and let it flow. That easy.

We'll take a little bit of Van Dyke Brown. Only God can make a tree - but you can paint one. That's what makes life fun. That you can make these decisions. That you can create the world that you want. If you don't think every day is a good day - try missing a few. You'll see. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right. Just think about these things in your mind and drop em' on canvas. It's beautiful - and we haven't even done anything to it yet. Clouds are free. They just float around the sky all day and have fun. Now then, let's play. It is a lot of fun. Don't fiddle with it all day. Painting should do one thing. It should put happiness in your heart. We'll put all the little clouds in and let them dance around and have fun. This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.

Let's do that again. There it is. Everything's not great in life, but we can still find beauty in it. Now we don't want him to get lonely, so we'll give him a little friend. Let's get wild today. The little tiny Tim easels will let you down. We touch the canvas, the canvas takes what it wants. The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start. We don't make mistakes we just have happy little accidents. Look at them little rascals. It looks so good, I might as well not stop. All you need to paint is a few tools, a little instruction, and a vision in your mind. You gotta think like a tree.

And maybe, maybe, maybe... That easy. This is probably the greatest thing that's ever happened in my life. And maybe a little bush lives there. This is probably the greatest thing to happen in my life - to be able to share this with you. You don't have to be crazy to do this but it does help. You can create beautiful things - but you have to see them in your mind first. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. Use your imagination, let it go. There we are. This present moment is perfect simply due to the fact you're experiencing it. We'll have a super time. In nature, dead trees are just as normal as live trees. Put it in, leave it alone. But they're very easily killed. Clouds are delicate.

Now we'll take the almighty fan brush. No pressure. Just relax and watch it happen. We'll lay all these little funky little things in there. A big strong tree needs big strong roots. Everyone wants to enjoy the good parts - but you have to build the framework first. We're trying to teach you a technique here and how to use it. We can always carry this a step further. There's really no end to this. This is a happy place, little squirrels live here and play. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. We need a shadow side and a highlight side. Be so very light. Be a gentle whisper.

There's nothing wrong with having a tree as a friend. You need the dark in order to show the light. Fluff that up. When you buy that first tube of paint it gives you an artist license. Everyone is going to see things differently - and that's the way it should be. Anytime you learn something your time and energy are not wasted. All you have to learn here is how to have fun. Brown is such a nice color. The only prerequisite is that it makes you happy. If it makes you happy then it's good. We want to use a lot pressure while using no pressure at all. Don't fight it, use what happens. All you have to do is let your imagination go wild. Just go back and put one little more happy tree in there.

It's a super day, so why not make a beautiful sky? Very easy to work these to death. How do you make a round circle with a square knife? That's your challenge for the day. A happy cloud. Give him a friend, we forget the trees get lonely too. Just let this happen. We just let this flow right out of our minds. You can't have light without dark. You can't know happiness unless you've known sorrow. That's the way I look when I get home late; black and blue. Sometimes you learn more from your mistakes than you do from your masterpieces. Work that paint. Trees get lonely too, so we'll give him a little friend.


          </div>
          <div id="foo5">
            <span className="display-2 text-muted d-block">ESTE ES EL QUINTO</span>
That's what painting is all about. It should make you feel good when you paint. We have a fantastic little sky! If you do too much it's going to lose its effectiveness. If you hypnotize it, it will go away. This is the way you take out your flustrations. You can do anything your heart can imagine. Just let these leaves jump off the brush Just use the old one inch brush. Trees live in your fan brush, but you have to scare them out. Mix your color marbly don't mix it dead. Be careful. You can always add more - but you can't take it away. Let's make some happy little clouds in our world. There comes a nice little fluffer. Let's put some happy trees and bushes back in here.

Just beat the devil out of it. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a nice tree right here. Have fun with it. Just make a decision and let it go. With practice comes confidence. I sincerely wish for you every possible joy life could bring. Pretend you're water. Just floating without any effort. Having a good day. No worries. No cares. Just float and wait for the wind to blow you around. Maybe there's a little something happening right here. You can do anything here - the only pre-requisite is that it makes you happy.

Even trees need a friend. We all need friends. Everybody needs a friend. See there, told you that would be easy. So often we avoid running water, and running water is a lot of fun. There are no mistakes. You can fix anything that happens. In your world you have total and absolute power. Tree trunks grow however makes them happy. Maybe there's a happy little Evergreen that lives here. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. I thought today we would make a happy little stream that's just running through the woods here. Work on one thing at a time. Don't get carried away - we have plenty of time. A fan brush can be your best friend. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.

Learn when to stop. They say everything looks better with odd numbers of things. But sometimes I put even numbers—just to upset the critics. There we go. This is truly an almighty mountain. Think about a cloud. Just float around and be there. God gave you this gift of imagination. Use it. Get away from those little Christmas tree things we used to make in school. Imagination is the key to painting. Decide where your cloud lives. Maybe he lives right in here. Let that brush dance around there and play. We'll throw some happy little limbs on this tree. Isn't it great to do something you can't fail at? Let's go up in here, and start having some fun

We don't need any guidelines or formats. All we need to do is just let it flow right out of us. Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect. We'll put a happy little bush here. See. We take the corner of the brush and let it play back-and-forth. Don't forget to tell these special people in your life just how special they are to you. Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying. We start with a vision in our heart, and we put it on canvas. Isn't that fantastic that you can create an almighty tree that fast? There isn't a rule. You just practice and find out which way works best for you. It's almost like something out of a fairytale book. I'm a water fanatic. I love water. You can create anything that makes you happy. I thought today we would do a happy little picture. Isn't that fantastic? You can just push a little tree out of your brush like that.

I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things. Here's something that's fun. You better get your coat out, this is going to be a cold painting. These trees are so much fun. I get started on them and I have a hard time stopping. Just take out whatever you don't want. It'll change your entire perspective. Maybe there's a happy little waterfall happening over here. Here we're limited by the time we have. Absolutely no pressure. You are just a whisper floating across a mountain. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You are only limited by your imagination.

In your imagination you can go anywhere you want. There we go. Without washing the brush, I'm gonna go right into some Van Dyke Brown, some Burnt Umber, and a little bit of Sap Green. Steve wants reflections, so let's give him reflections. Little short strokes. Put your feelings into it, your heart, it's your world. In your world you can create anything you desire. The least little bit can do so much. Don't be bashful drop me a line. A beautiful little sunset. Don't kill all your dark areas - you need them to show the light. From all of us here, I want to wish you happy painting and God bless, my friends.

We don't really know where this goes - and I'm not sure we really care. If what you're doing doesn't make you happy - you're doing the wrong thing. You can spend all day playing with mountains. Just go out and talk to a tree. Make friends with it. You create the dream - then you bring it into your world. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. Isn't it fantastic that you can change your mind and create all these happy things? Just make little strokes like that. Let's put some highlights on these little trees. The sun wouldn't forget them. You've got to learn to fight the temptation to resist these things. Just let them happen. There are no limits in this world. Let your imagination be your guide. Let all these things just sort of happen. You can work and carry-on and put lots of little happy things in here. If it's not what you want - stop and change it. Don't just keep going and expect it will get better.

Let's put some happy little bushes on the other side now. Let your imagination be your guide. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. You're meant to have fun in life. You have to make those little noises or it won't work. Let's get crazy. Making all those little fluffies that live in the clouds. But we're not there yet, so we don't need to worry about it. Water's like me. It's laaazy ... Boy, it always looks for the easiest way to do things That's crazy. Every time you practice, you learn more. Just relax and let it flow. That easy.

We'll take a little bit of Van Dyke Brown. Only God can make a tree - but you can paint one. That's what makes life fun. That you can make these decisions. That you can create the world that you want. If you don't think every day is a good day - try missing a few. You'll see. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right. Just think about these things in your mind and drop em' on canvas. It's beautiful - and we haven't even done anything to it yet. Clouds are free. They just float around the sky all day and have fun. Now then, let's play. It is a lot of fun. Don't fiddle with it all day. Painting should do one thing. It should put happiness in your heart. We'll put all the little clouds in and let them dance around and have fun. This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.

Let's do that again. There it is. Everything's not great in life, but we can still find beauty in it. Now we don't want him to get lonely, so we'll give him a little friend. Let's get wild today. The little tiny Tim easels will let you down. We touch the canvas, the canvas takes what it wants. The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start. We don't make mistakes we just have happy little accidents. Look at them little rascals. It looks so good, I might as well not stop. All you need to paint is a few tools, a little instruction, and a vision in your mind. You gotta think like a tree.

And maybe, maybe, maybe... That easy. This is probably the greatest thing that's ever happened in my life. And maybe a little bush lives there. This is probably the greatest thing to happen in my life - to be able to share this with you. You don't have to be crazy to do this but it does help. You can create beautiful things - but you have to see them in your mind first. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. Use your imagination, let it go. There we are. This present moment is perfect simply due to the fact you're experiencing it. We'll have a super time. In nature, dead trees are just as normal as live trees. Put it in, leave it alone. But they're very easily killed. Clouds are delicate.

Now we'll take the almighty fan brush. No pressure. Just relax and watch it happen. We'll lay all these little funky little things in there. A big strong tree needs big strong roots. Everyone wants to enjoy the good parts - but you have to build the framework first. We're trying to teach you a technique here and how to use it. We can always carry this a step further. There's really no end to this. This is a happy place, little squirrels live here and play. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. We need a shadow side and a highlight side. Be so very light. Be a gentle whisper.

There's nothing wrong with having a tree as a friend. You need the dark in order to show the light. Fluff that up. When you buy that first tube of paint it gives you an artist license. Everyone is going to see things differently - and that's the way it should be. Anytime you learn something your time and energy are not wasted. All you have to learn here is how to have fun. Brown is such a nice color. The only prerequisite is that it makes you happy. If it makes you happy then it's good. We want to use a lot pressure while using no pressure at all. Don't fight it, use what happens. All you have to do is let your imagination go wild. Just go back and put one little more happy tree in there.

It's a super day, so why not make a beautiful sky? Very easy to work these to death. How do you make a round circle with a square knife? That's your challenge for the day. A happy cloud. Give him a friend, we forget the trees get lonely too. Just let this happen. We just let this flow right out of our minds. You can't have light without dark. You can't know happiness unless you've known sorrow. That's the way I look when I get home late; black and blue. Sometimes you learn more from your mistakes than you do from your masterpieces. Work that paint. Trees get lonely too, so we'll give him a little friend.


          </div>
          <div id="foo6">
That's what painting is all about. It should make you feel good when you paint. We have a fantastic little sky! If you do too much it's going to lose its effectiveness. If you hypnotize it, it will go away. This is the way you take out your flustrations. You can do anything your heart can imagine. Just let these leaves jump off the brush Just use the old one inch brush. Trees live in your fan brush, but you have to scare them out. Mix your color marbly don't mix it dead. Be careful. You can always add more - but you can't take it away. Let's make some happy little clouds in our world. There comes a nice little fluffer. Let's put some happy trees and bushes back in here.

Just beat the devil out of it. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a nice tree right here. Have fun with it. Just make a decision and let it go. With practice comes confidence. I sincerely wish for you every possible joy life could bring. Pretend you're water. Just floating without any effort. Having a good day. No worries. No cares. Just float and wait for the wind to blow you around. Maybe there's a little something happening right here. You can do anything here - the only pre-requisite is that it makes you happy.

Even trees need a friend. We all need friends. Everybody needs a friend. See there, told you that would be easy. So often we avoid running water, and running water is a lot of fun. There are no mistakes. You can fix anything that happens. In your world you have total and absolute power. Tree trunks grow however makes them happy. Maybe there's a happy little Evergreen that lives here. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. I thought today we would make a happy little stream that's just running through the woods here. Work on one thing at a time. Don't get carried away - we have plenty of time. A fan brush can be your best friend. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.

Learn when to stop. They say everything looks better with odd numbers of things. But sometimes I put even numbers—just to upset the critics. There we go. This is truly an almighty mountain. Think about a cloud. Just float around and be there. God gave you this gift of imagination. Use it. Get away from those little Christmas tree things we used to make in school. Imagination is the key to painting. Decide where your cloud lives. Maybe he lives right in here. Let that brush dance around there and play. We'll throw some happy little limbs on this tree. Isn't it great to do something you can't fail at? Let's go up in here, and start having some fun

We don't need any guidelines or formats. All we need to do is just let it flow right out of us. Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect. We'll put a happy little bush here. See. We take the corner of the brush and let it play back-and-forth. Don't forget to tell these special people in your life just how special they are to you. Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying. We start with a vision in our heart, and we put it on canvas. Isn't that fantastic that you can create an almighty tree that fast? There isn't a rule. You just practice and find out which way works best for you. It's almost like something out of a fairytale book. I'm a water fanatic. I love water. You can create anything that makes you happy. I thought today we would do a happy little picture. Isn't that fantastic? You can just push a little tree out of your brush like that.

I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things. Here's something that's fun. You better get your coat out, this is going to be a cold painting. These trees are so much fun. I get started on them and I have a hard time stopping. Just take out whatever you don't want. It'll change your entire perspective. Maybe there's a happy little waterfall happening over here. Here we're limited by the time we have. Absolutely no pressure. You are just a whisper floating across a mountain. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You are only limited by your imagination.

In your imagination you can go anywhere you want. There we go. Without washing the brush, I'm gonna go right into some Van Dyke Brown, some Burnt Umber, and a little bit of Sap Green. Steve wants reflections, so let's give him reflections. Little short strokes. Put your feelings into it, your heart, it's your world. In your world you can create anything you desire. The least little bit can do so much. Don't be bashful drop me a line. A beautiful little sunset. Don't kill all your dark areas - you need them to show the light. From all of us here, I want to wish you happy painting and God bless, my friends.

We don't really know where this goes - and I'm not sure we really care. If what you're doing doesn't make you happy - you're doing the wrong thing. You can spend all day playing with mountains. Just go out and talk to a tree. Make friends with it. You create the dream - then you bring it into your world. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. Isn't it fantastic that you can change your mind and create all these happy things? Just make little strokes like that. Let's put some highlights on these little trees. The sun wouldn't forget them. You've got to learn to fight the temptation to resist these things. Just let them happen. There are no limits in this world. Let your imagination be your guide. Let all these things just sort of happen. You can work and carry-on and put lots of little happy things in here. If it's not what you want - stop and change it. Don't just keep going and expect it will get better.

Let's put some happy little bushes on the other side now. Let your imagination be your guide. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. You're meant to have fun in life. You have to make those little noises or it won't work. Let's get crazy. Making all those little fluffies that live in the clouds. But we're not there yet, so we don't need to worry about it. Water's like me. It's laaazy ... Boy, it always looks for the easiest way to do things That's crazy. Every time you practice, you learn more. Just relax and let it flow. That easy.

We'll take a little bit of Van Dyke Brown. Only God can make a tree - but you can paint one. That's what makes life fun. That you can make these decisions. That you can create the world that you want. If you don't think every day is a good day - try missing a few. You'll see. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right. Just think about these things in your mind and drop em' on canvas. It's beautiful - and we haven't even done anything to it yet. Clouds are free. They just float around the sky all day and have fun. Now then, let's play. It is a lot of fun. Don't fiddle with it all day. Painting should do one thing. It should put happiness in your heart. We'll put all the little clouds in and let them dance around and have fun. This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.

Let's do that again. There it is. Everything's not great in life, but we can still find beauty in it. Now we don't want him to get lonely, so we'll give him a little friend. Let's get wild today. The little tiny Tim easels will let you down. We touch the canvas, the canvas takes what it wants. The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start. We don't make mistakes we just have happy little accidents. Look at them little rascals. It looks so good, I might as well not stop. All you need to paint is a few tools, a little instruction, and a vision in your mind. You gotta think like a tree.

And maybe, maybe, maybe... That easy. This is probably the greatest thing that's ever happened in my life. And maybe a little bush lives there. This is probably the greatest thing to happen in my life - to be able to share this with you. You don't have to be crazy to do this but it does help. You can create beautiful things - but you have to see them in your mind first. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. Use your imagination, let it go. There we are. This present moment is perfect simply due to the fact you're experiencing it. We'll have a super time. In nature, dead trees are just as normal as live trees. Put it in, leave it alone. But they're very easily killed. Clouds are delicate.

Now we'll take the almighty fan brush. No pressure. Just relax and watch it happen. We'll lay all these little funky little things in there. A big strong tree needs big strong roots. Everyone wants to enjoy the good parts - but you have to build the framework first. We're trying to teach you a technique here and how to use it. We can always carry this a step further. There's really no end to this. This is a happy place, little squirrels live here and play. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. We need a shadow side and a highlight side. Be so very light. Be a gentle whisper.

There's nothing wrong with having a tree as a friend. You need the dark in order to show the light. Fluff that up. When you buy that first tube of paint it gives you an artist license. Everyone is going to see things differently - and that's the way it should be. Anytime you learn something your time and energy are not wasted. All you have to learn here is how to have fun. Brown is such a nice color. The only prerequisite is that it makes you happy. If it makes you happy then it's good. We want to use a lot pressure while using no pressure at all. Don't fight it, use what happens. All you have to do is let your imagination go wild. Just go back and put one little more happy tree in there.

It's a super day, so why not make a beautiful sky? Very easy to work these to death. How do you make a round circle with a square knife? That's your challenge for the day. A happy cloud. Give him a friend, we forget the trees get lonely too. Just let this happen. We just let this flow right out of our minds. You can't have light without dark. You can't know happiness unless you've known sorrow. That's the way I look when I get home late; black and blue. Sometimes you learn more from your mistakes than you do from your masterpieces. Work that paint. Trees get lonely too, so we'll give him a little friend.


          </div>
          <div id="foo7">
That's what painting is all about. It should make you feel good when you paint. We have a fantastic little sky! If you do too much it's going to lose its effectiveness. If you hypnotize it, it will go away. This is the way you take out your flustrations. You can do anything your heart can imagine. Just let these leaves jump off the brush Just use the old one inch brush. Trees live in your fan brush, but you have to scare them out. Mix your color marbly don't mix it dead. Be careful. You can always add more - but you can't take it away. Let's make some happy little clouds in our world. There comes a nice little fluffer. Let's put some happy trees and bushes back in here.

Just beat the devil out of it. I really believe that if you practice enough you could paint the 'Mona Lisa' with a two-inch brush. Let's have a nice tree right here. Have fun with it. Just make a decision and let it go. With practice comes confidence. I sincerely wish for you every possible joy life could bring. Pretend you're water. Just floating without any effort. Having a good day. No worries. No cares. Just float and wait for the wind to blow you around. Maybe there's a little something happening right here. You can do anything here - the only pre-requisite is that it makes you happy.

Even trees need a friend. We all need friends. Everybody needs a friend. See there, told you that would be easy. So often we avoid running water, and running water is a lot of fun. There are no mistakes. You can fix anything that happens. In your world you have total and absolute power. Tree trunks grow however makes them happy. Maybe there's a happy little Evergreen that lives here. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it. I thought today we would make a happy little stream that's just running through the woods here. Work on one thing at a time. Don't get carried away - we have plenty of time. A fan brush can be your best friend. And that's when it becomes fun - you don't have to spend your time thinking about what's happening - you just let it happen.

Learn when to stop. They say everything looks better with odd numbers of things. But sometimes I put even numbers—just to upset the critics. There we go. This is truly an almighty mountain. Think about a cloud. Just float around and be there. God gave you this gift of imagination. Use it. Get away from those little Christmas tree things we used to make in school. Imagination is the key to painting. Decide where your cloud lives. Maybe he lives right in here. Let that brush dance around there and play. We'll throw some happy little limbs on this tree. Isn't it great to do something you can't fail at? Let's go up in here, and start having some fun

We don't need any guidelines or formats. All we need to do is just let it flow right out of us. Trees grow in all kinds of ways. They're not all perfectly straight. Not every limb is perfect. We'll put a happy little bush here. See. We take the corner of the brush and let it play back-and-forth. Don't forget to tell these special people in your life just how special they are to you. Almost everything is going to happen for you automatically - you don't have to spend any time working or worrying. We start with a vision in our heart, and we put it on canvas. Isn't that fantastic that you can create an almighty tree that fast? There isn't a rule. You just practice and find out which way works best for you. It's almost like something out of a fairytale book. I'm a water fanatic. I love water. You can create anything that makes you happy. I thought today we would do a happy little picture. Isn't that fantastic? You can just push a little tree out of your brush like that.

I was blessed with a very steady hand; and it comes in very handy when you're doing these little delicate things. Here's something that's fun. You better get your coat out, this is going to be a cold painting. These trees are so much fun. I get started on them and I have a hard time stopping. Just take out whatever you don't want. It'll change your entire perspective. Maybe there's a happy little waterfall happening over here. Here we're limited by the time we have. Absolutely no pressure. You are just a whisper floating across a mountain. Look around, look at what we have. Beauty is everywhere, you only have to look to see it. Van Dyke Brown is a very nice brown, it's almost like a chocolate brown. You are only limited by your imagination.

In your imagination you can go anywhere you want. There we go. Without washing the brush, I'm gonna go right into some Van Dyke Brown, some Burnt Umber, and a little bit of Sap Green. Steve wants reflections, so let's give him reflections. Little short strokes. Put your feelings into it, your heart, it's your world. In your world you can create anything you desire. The least little bit can do so much. Don't be bashful drop me a line. A beautiful little sunset. Don't kill all your dark areas - you need them to show the light. From all of us here, I want to wish you happy painting and God bless, my friends.

We don't really know where this goes - and I'm not sure we really care. If what you're doing doesn't make you happy - you're doing the wrong thing. You can spend all day playing with mountains. Just go out and talk to a tree. Make friends with it. You create the dream - then you bring it into your world. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe. Isn't it fantastic that you can change your mind and create all these happy things? Just make little strokes like that. Let's put some highlights on these little trees. The sun wouldn't forget them. You've got to learn to fight the temptation to resist these things. Just let them happen. There are no limits in this world. Let your imagination be your guide. Let all these things just sort of happen. You can work and carry-on and put lots of little happy things in here. If it's not what you want - stop and change it. Don't just keep going and expect it will get better.

Let's put some happy little bushes on the other side now. Let your imagination be your guide. We're not trying to teach you a thing to copy. We're just here to teach you a technique, then let you loose into the world. You're meant to have fun in life. You have to make those little noises or it won't work. Let's get crazy. Making all those little fluffies that live in the clouds. But we're not there yet, so we don't need to worry about it. Water's like me. It's laaazy ... Boy, it always looks for the easiest way to do things That's crazy. Every time you practice, you learn more. Just relax and let it flow. That easy.

We'll take a little bit of Van Dyke Brown. Only God can make a tree - but you can paint one. That's what makes life fun. That you can make these decisions. That you can create the world that you want. If you don't think every day is a good day - try missing a few. You'll see. And I know you're saying, 'Oh Bob, you've done it this time.' And you may be right. Just think about these things in your mind and drop em' on canvas. It's beautiful - and we haven't even done anything to it yet. Clouds are free. They just float around the sky all day and have fun. Now then, let's play. It is a lot of fun. Don't fiddle with it all day. Painting should do one thing. It should put happiness in your heart. We'll put all the little clouds in and let them dance around and have fun. This is the time to get out all your flustrations, much better than kicking the dog around the house or taking it out on your spouse.

Let's do that again. There it is. Everything's not great in life, but we can still find beauty in it. Now we don't want him to get lonely, so we'll give him a little friend. Let's get wild today. The little tiny Tim easels will let you down. We touch the canvas, the canvas takes what it wants. The first step to doing anything is to believe you can do it. See it finished in your mind before you ever start. We don't make mistakes we just have happy little accidents. Look at them little rascals. It looks so good, I might as well not stop. All you need to paint is a few tools, a little instruction, and a vision in your mind. You gotta think like a tree.

And maybe, maybe, maybe... That easy. This is probably the greatest thing that's ever happened in my life. And maybe a little bush lives there. This is probably the greatest thing to happen in my life - to be able to share this with you. You don't have to be crazy to do this but it does help. You can create beautiful things - but you have to see them in your mind first. You're the greatest thing that has ever been or ever will be. You're special. You're so very special. Use your imagination, let it go. There we are. This present moment is perfect simply due to the fact you're experiencing it. We'll have a super time. In nature, dead trees are just as normal as live trees. Put it in, leave it alone. But they're very easily killed. Clouds are delicate.

Now we'll take the almighty fan brush. No pressure. Just relax and watch it happen. We'll lay all these little funky little things in there. A big strong tree needs big strong roots. Everyone wants to enjoy the good parts - but you have to build the framework first. We're trying to teach you a technique here and how to use it. We can always carry this a step further. There's really no end to this. This is a happy place, little squirrels live here and play. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. We need a shadow side and a highlight side. Be so very light. Be a gentle whisper.

There's nothing wrong with having a tree as a friend. You need the dark in order to show the light. Fluff that up. When you buy that first tube of paint it gives you an artist license. Everyone is going to see things differently - and that's the way it should be. Anytime you learn something your time and energy are not wasted. All you have to learn here is how to have fun. Brown is such a nice color. The only prerequisite is that it makes you happy. If it makes you happy then it's good. We want to use a lot pressure while using no pressure at all. Don't fight it, use what happens. All you have to do is let your imagination go wild. Just go back and put one little more happy tree in there.

It's a super day, so why not make a beautiful sky? Very easy to work these to death. How do you make a round circle with a square knife? That's your challenge for the day. A happy cloud. Give him a friend, we forget the trees get lonely too. Just let this happen. We just let this flow right out of our minds. You can't have light without dark. You can't know happiness unless you've known sorrow. That's the way I look when I get home late; black and blue. Sometimes you learn more from your mistakes than you do from your masterpieces. Work that paint. Trees get lonely too, so we'll give him a little friend.


          </div>
        </section>
      </div>
    )
  }
}
